version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mevn-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mevndb
      - NODE_ENV=production
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mevn-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mevn-network

networks:
  mevn-network:
    driver: bridge

volumes:
  mongo-data:
