version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
