version: '2.8'

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:

